### ISSUE TITLE
Module does not run on puppet version 5.x 

### ISSUE THREAD

**Issue by zehweh** [example42/puppet-rclocal#10]
## Expected Behavior 

Successful run on puppet version 5.x

## Actual Behavior

Errors like:
Resource type not found: RedHat at [..]modules/rclocal/manifests/params.pp:12:5
and
Error while evaluating a Function Call, hiera() can only be called using the 4.x function API

## Steps to Reproduce the Problem

  1. run code on puppet version 5.x

**Comment by alvagante** [comment]
What version of the puppi module are you using? The params_lookup function, which you removed in your PR, actually works on Puppet 5. Just get a recent version of the puppi module , with updated params_lookup

**Comment by zehweh** [comment]
You are right, I used an outdated version of puppi.
The latest version works - thanks!
