### ISSUE TITLE
SysVStartPriority= has been removed and it is ignored

### ISSUE THREAD

**Issue by jamesj2** [example42/puppet-rclocal#24]
Upstream systemd change seems to have broken the rc-local service running on CentOS Linux release 7.8.2003 (Core).

## Expected Behavior 
rc-local service start without error

## Actual Behavior
Error: Systemd start for rc-local failed!
journalctl log for rc-local:
-- Logs begin at Fri 2020-08-28 10:55:18 CDT, end at Fri 2020-08-28 13:49:46 CDT. --
Aug 28 13:49:46 cbizfile2 systemd[1]: [/etc/systemd/system/rc-local.service:11] Support for option SysVStartPriority  has been removed and it is ignored
Aug 28 13:49:46 file2 systemd[1]: Starting rc.local Compatibility...
Aug 28 13:49:46 file2 systemd[11961]: Failed at step STDOUT spawning /etc/rc.d/rc.local: Inappropriate ioctl for device
Aug 28 13:49:46 file2 systemd[1]: rc-local.service: control process exited, code=exited status=209
Aug 28 13:49:46 file2 systemd[1]: Failed to start rc.local Compatibility.
Aug 28 13:49:46 file2 systemd[1]: Unit rc-local.service entered failed state.
Aug 28 13:49:46 file2 systemd[1]: rc-local.service failed.

Error: /Stage[main]/Rclocal/Service[rc-local]/ensure: change from 'stopped' to 'running' failed: Systemd start for rc-local failed!
journalctl log for rc-local:
-- Logs begin at Fri 2020-08-28 10:55:18 CDT, end at Fri 2020-08-28 13:49:46 CDT. --
Aug 28 13:49:46 file2 systemd[1]: [/etc/systemd/system/rc-local.service:11] Support for option SysVStartPriority= has been removed and it is ignored
Aug 28 13:49:46 file2 systemd[1]: Starting rc.local Compatibility...
Aug 28 13:49:46 file2 systemd[11961]: Failed at step STDOUT spawning /etc/rc.d/rc.local: Inappropriate ioctl for device
Aug 28 13:49:46 file2 systemd[1]: rc-local.service: control process exited, code=exited status=209
Aug 28 13:49:46 file2 systemd[1]: Failed to start rc.local Compatibility.
Aug 28 13:49:46 file2 systemd[1]: Unit rc-local.service entered failed state.
Aug 28 13:49:46 file2 systemd[1]: rc-local.service failed.
 (corrective)

**Comment by alvagante** [comment]
It looks like the option  SysVStartPriority is simply ignored and shouldn't be the reason of the failure (Failed at step STDOUT spawning /etc/rc.d/rc.local: Inappropriate ioctl for device)
Does the service start if you remove the line with SysVStartPriority ?

**Comment by jamesj2** [comment]
So I checked the service by hand and it's was already started and I was able to restart it by hand.  It must have been something else.  I've rebooted since creating this issue.  Maybe systemd needed a restart.  Thanks!
