### ISSUE TITLE
metadata.json permissions changed between v2.0.5 and v2.0.7

### ISSUE THREAD

**Issue by aharden** [example42/puppet-rclocal#9]
I'm upgrading the modules in our site's Puppetfile and was upgrading this module from v2.0.5 to v2.0.7.  It caused the following error: 
Error: /File[/var/opt/lib/pe-puppet/facts.d]: Failed to generate additional resources using 'eval_generate': Error 400 on SERVER: Permission denied - /etc/puppetlabs/puppet/environments/feature_PUP439_tecontrol/modules/rclocal/metadata.json
Error: /File[/var/opt/lib/pe-puppet/facts.d]: Could not evaluate: Could not retrieve file metadata for puppet://puppetsandbox.tycoelectronics.net/pluginfacts: Error 400 on SERVER: Permission denied - /etc/puppetlabs/puppet/environments/feature_PUP439_tecontrol/modules/rclocal/metadata.json

Comparing the file permissions of metadata.json for the two releases:
v2.0.5:
-r--r--r--  1 root root  931 Oct 25  2013 metadata.json
v2.0.7:
-r--------  1 root root  521 Aug 18 09:45 metadata.json

The change in metadata.json file permissions is causing this issue.

I would put in a PR to change this, but you haven't included metadata.json in this repo.  You must be adding it when publishing the module to the Forge.

Thanks.

**Comment by alvagante** [comment]
I've pushed v.2.0.8 to the forge, can you verify if the issue is solved?

**Comment by aharden** [comment]
On both a test PE 3.8.2 master and my workstation, v2.0.8 pulls down with a metadata.json that is still 0400.

**Comment by alvagante** [comment]
I've made some mess with the umask on the machine where modules were packed and pushed.
Uploaded a new version, this should be ok, please let me know (and sorry).
Going to check the other modules....

**Comment by aharden** [comment]
Looks good.  Thanks!
-Alex
